# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ebBUm2KFp0Jt0VBDkzukHR-zwfPJ5N4Z
"""

from google.colab import files
import zipfile
import os

# Upload your dataset.zip (keep your existing code)
uploaded = files.upload()  # Choose dataset.zip

with zipfile.ZipFile("dataset.zip", 'r') as zip_ref:
    zip_ref.extractall("dataset")

# Confirm folder names
print("Dataset folders:", os.listdir("dataset"))

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import collections

# Enhanced data augmentation for training
train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,

    # More aggressive augmentation
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.15,
    zoom_range=0.2,
    horizontal_flip=True,
    brightness_range=[0.9, 1.1],
    fill_mode='nearest'
)

# Only rescaling for validation
val_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

# Use larger image size (224x224 is standard for transfer learning)
target_size = (224, 224)
batch_size = 16  # Smaller batch size often works better

train_gen = train_datagen.flow_from_directory(
    'dataset',
    target_size=target_size,
    batch_size=batch_size,
    class_mode='binary',
    subset='training',
    shuffle=True
)

val_gen = val_datagen.flow_from_directory(
    'dataset',
    target_size=target_size,
    batch_size=batch_size,
    class_mode='binary',
    subset='validation',
    shuffle=False
)

# Check your data
print(f"Training samples: {train_gen.samples}")
print(f"Validation samples: {val_gen.samples}")
print(f"Class indices: {train_gen.class_indices}")

# Check class balance
def check_class_balance(generator):
    counter = collections.Counter(generator.classes)
    total = sum(counter.values())
    for class_id, count in counter.items():
        class_name = [k for k, v in generator.class_indices.items() if v == class_id][0]
        print(f"Class '{class_name}': {count} samples ({count/total*100:.1f}%)")
    return counter

print("\nClass distribution:")
train_balance = check_class_balance(train_gen)

print("Creating improved custom CNN...")
from tensorflow.keras import layers, models
from tensorflow.keras.applications import VGG16
from tensorflow.keras.optimizers import Adam
model = models.Sequential([
    layers.Input(shape=(224, 224, 3)),

    # First block
    layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
    layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25),

    # Second block
    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    layers.Conv2D(64, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25),

    # Third block
    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.Conv2D(128, (3, 3), activation='relu', padding='same'),
    layers.MaxPooling2D((2, 2)),
    layers.Dropout(0.25),

    # Dense layers
    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(1, activation='sigmoid')
])


# Compile model
model.compile(
    optimizer=Adam(learning_rate=0.0001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print(model.summary())

from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint

# Setup callbacks for better training
callbacks = [
    EarlyStopping(
        monitor='val_accuracy',
        patience=10,
        restore_best_weights=True,
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.2,
        patience=5,
        min_lr=1e-7,
        verbose=1
    ),
    ModelCheckpoint(
        'best_model.h5',
        monitor='val_accuracy',
        save_best_only=True,
        verbose=1
    )
]

# Handle class imbalance (if your dataset is imbalanced)
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

class_weights = compute_class_weight(
    'balanced',
    classes=np.unique(train_gen.classes),
    y=train_gen.classes
)
class_weight_dict = dict(enumerate(class_weights))
print(f"Class weights: {class_weight_dict}")

print("Starting training...")

# Train the model
history = model.fit(
    train_gen,
    validation_data=val_gen,
    epochs=25,  # Start with fewer epochs, increase if needed
    callbacks=callbacks,
    class_weight=class_weight_dict,
    verbose=1
)

if 'base_model' in locals():
    print("\nStarting fine-tuning...")

    # Unfreeze some layers
    base_model.trainable = True

    # Freeze early layers, unfreeze later ones
    for layer in base_model.layers[:-4]:  # Freeze all except last 4 layers
        layer.trainable = False

    # Recompile with lower learning rate
    model.compile(
        optimizer=Adam(learning_rate=0.00001),  # Much lower learning rate
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    # Continue training
    history_fine = model.fit(
        train_gen,
        validation_data=val_gen,
        epochs=10,  # Fewer epochs for fine-tuning
        initial_epoch=len(history.history['loss']),
        callbacks=callbacks,
        class_weight=class_weight_dict,
        verbose=1
    )

    # Combine histories for plotting
    for key in history.history:
        history.history[key].extend(history_fine.history[key])



model.save("improved_dog_classifier.h5" ,include_optimizer=False)
print("Model saved as 'improved_dog_classifier.h5'")


#

import tensorflow as tf

# Load your original model
model = tf.keras.models.load_model('improved_dog_classifier.h5')

# Convert to TensorFlow Lite with quantization
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]  # Use float16 instead of float32

# Convert and save
tflite_model = converter.convert()
with open('model_compressed.tflite', 'wb') as f:
    f.write(tflite_model)

import tensorflow as tf
import os

# Load your original model
print("Loading original model...")
model = tf.keras.models.load_model('improved_dog_classifier.h5')

print(f"Original model size: {os.path.getsize('improved_dog_classifier.h5') / (1024*1024):.1f} MB")

# Convert to TensorFlow Lite with quantization
print("Converting to TensorFlow Lite with quantization...")
converter = tf.lite.TFLiteConverter.from_keras_model(model)

# Apply optimizations for maximum compression
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]

# Convert the model
tflite_model = converter.convert()

# Save the quantized model
with open('model_quantized.tflite', 'wb') as f:
    f.write(tflite_model)

print(f"Quantized model size: {len(tflite_model) / (1024*1024):.1f} MB")
print(f"Size reduction: {(1 - len(tflite_model) / os.path.getsize('improved_dog_classifier.h5')) * 100:.1f}%")
print("\nQuantized model saved as 'model_quantized.tflite'")
print("Now upload this file to Google Drive and get the sharing link!")

